name: Talker
packageVersion: v1.0.0
description: ROS Publisher
bindable: true
plans:
- name: default
  metadata: {}
  singleton: false
  components:
  - name: talker-component
    description: ''
    cloudInfra:
      replicas: 1
      endpoints: []
    ros:
      topics:
      - name: "/telemetry"
        qos: max
        compression: ''
        scoped: false
        targeted: false
      services: []
      actions: []
      isROS: true
      ros_distro: kinetic
    requiredRuntime: cloud
    architecture: amd64
    executables:
    - name: talker-executable
      simulationOptions:
        simulation: false
      buildGUID:
      cmd:
      - roslaunch talker talker.launch
      limits:
        cpu: 0.5
        memory: 2048
    parameters: []
    rosBagJobDefs: []
  includePackages: []
  dependentDeployments: []
  inboundROSInterfaces:
    anyIncomingScopedOrTargetedRosConfig: false
  exposedParameters: []
